### ISSUE TITLE
兄dei还在开发吗？我觉得这个可以做个商业化的。

### ISSUE THREAD

**Issue by yinzhuce** [geeeeeeeek/oneNFS#4]

**Comment by geeeeeeeek** [comment]
如何商业化？

yinzhuce <notifications@github.com> 于2019年9月2日周一 下午2:15写道：

**Comment by Erichuang007** [comment]
不投入成本的请求别人的数据，或者自己不去拿一手数据，怕是还没开始商业化就被抓了

**Comment by enstan** [comment]
我用的是思维导图的思路
